language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -q ansible==2.8.1
script:
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook app/main.yml --syntax-check
  - ansible-playbook db/main.yml --syntax-check
  - ansible-playbook deployment/main.yml --syntax-check
  - ansible-playbook configure.yml --syntax-check
