language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -q ansible==2.8.1
script:
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook -i inventories/production/inventory ./app/main.yml --syntax-check
  - ansible-playbook -i inventories/production/inventory ./db/main.yml --syntax-check
  - ansible-playbook -i inventories/production/inventory ./deployment/main.yml --syntax-check
  - ansible-playbook -i inventories/production/inventory configure.yml --syntax-check
