---
- hosts: app
  become: yes
  roles:
    - role: geerlingguy.java
      vars:
        java_packages:
          - java-1.8.0-openjdk

    - role: tomcat-ansible-role
      vars:
        tomcat_version: 8.5.23
        tomcat_permissions_production: True
        tomcat_users:
          - username: "tomcat"
            password: "tomcat"
            roles: "tomcat,admin,manager,manager-gui"

