---
- hosts: app
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Copy application artifact with owner and permissions
      copy:
        src: "{{ artifact }}"
        dest: "{{ app_directory }}"
        owner: tomcat
        group: tomcat
      register: app_updated

    - name: Restart tomcat
      systemd:
        name: tomcat
        state: restarted
        daemon_reload: yes
      when: app_updated.changed
